version: "3.9"

services:
  db:
    env_file:
      - .env
    image: postgres:14.21-trixie
    container_name: cthelper-db
    ports:
      - "5432:5432"
    volumes:
      - cthelper_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    env_file:
      - .env
    build:
      context: ./CTHelper.Presentation
      dockerfile: Dockerfile
    container_name: cthelper-api
    depends_on:
      - db
    ports:
      - "5000:8080"
    restart: unless-stopped

volumes:
  cthelper_pgdata:
