services:
  db:
    image: postgres:14.21-trixie
    env_file:
      - .env
    ports:
      - "5000:5432"
    volumes:
      - cthelper_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - "5001:9000" #api
      - "5002:9001" #web-ui
    volumes:
      - minio_data:/data
    restart: unless-stopped

  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: CTHelper.Presentation/Dockerfile
    depends_on:
      - db
      - minio
    ports:
      - "5003:8080"
    restart: unless-stopped

volumes:
  cthelper_pgdata:
  minio_data:
